"""Pydantic schemas for Agent 2 — AI Financial Review Agent."""

from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field


class InvestigationItem(BaseModel):
    """Structured result of investigating an individual Agent 1 finding."""
    category: str = Field(..., description="VALIDATION, YOY, ML_ANOMALY, or RATIO")
    target: str = Field(..., description="Target metric or equation name")
    status: str = Field(..., description="Status flag: e.g. VALID, INVALID, FLAGGED, NORMAL, ANOMALY, COMPLETED, INCOMPLETE, UNDEFINED")
    description: str = Field(..., description="Factual description of the finding")
    evidence: List[str] = Field(default_factory=list, description="Traceable pointers to data evidence")
    reason: Optional[str] = Field(None, description="Detailed explanatory context or note")


class MetricComparisonItem(BaseModel):
    """Comparison between two related verified financial metrics."""
    metric_a: str = Field(..., description="First metric name")
    metric_a_value: Optional[float] = Field(None, description="First metric value")
    metric_b: str = Field(..., description="Second metric name")
    metric_b_value: Optional[float] = Field(None, description="Second metric value")
    relationship: str = Field(..., description="Deterministic relationship label (e.g. both_positive, diverging)")
    evidence: List[str] = Field(default_factory=list, description="Evidence paths for compared metrics")


class ObservationFinding(BaseModel):
    """Structured observation generated by LLM reasoning grounded in verified findings."""
    finding_type: str = Field(default="GENERAL", description="Category: VALIDATION, YOY, ML_ANOMALY, RATIO, RELATIONSHIP")
    title: str = Field(default="Observation", description="Short descriptive title of the observation")
    finding: str = Field(..., description="Factual statement of what was observed")
    explanation: str = Field(..., description="Reasoning based strictly on supplied evidence")
    severity: str = Field(default="UNKNOWN", description="Descriptive classification: LOW, MEDIUM, HIGH, UNKNOWN")
    evidence: List[str] = Field(default_factory=list, description="Referenced evidence keys or paths")
    recommendation: Optional[str] = Field(None, description="Actionable review recommendation")


class OllamaReviewContent(BaseModel):
    """Raw JSON contract expected from Ollama generate endpoint."""
    observations: List[ObservationFinding] = Field(default_factory=list, description="List of observations")
    summary: str = Field(default="Insufficient evidence.", description="High-level evidence-based review summary")
    limitations: List[str] = Field(default_factory=list, description="Noted data limitations or missing periods")


class Agent2ReviewResponse(BaseModel):
    """Canonical response contract for Agent 2 Financial Review."""
    document_id: str = Field(..., description="Document UUID")
    status: str = Field(..., description="COMPLETED, PARTIAL, or FAILED")
    investigations: List[InvestigationItem] = Field(default_factory=list, description="Deterministic findings investigations")
    metric_comparisons: List[MetricComparisonItem] = Field(default_factory=list, description="Paired metric comparisons")
    observations: List[ObservationFinding] = Field(default_factory=list, description="Observations from Ollama reasoning")
    summary: Optional[str] = Field(None, description="High-level narrative review summary")
    evidence: List[Dict[str, Any]] = Field(default_factory=list, description="Pass-through evidence items from Agent 1")
    warnings: List[str] = Field(default_factory=list, description="Diagnostic warnings aggregated across stages")
    reason: Optional[str] = Field(None, description="Explanatory notice if status is PARTIAL or FAILED")
    model: str = Field(..., description="Ollama model identifier used for reasoning")
